# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project Help' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project Help
	pod 'Alamofire', '~>2.0'
  	pod 'SwiftyJSON', '~> 2.3'
	pod 'LocationPicker', '~> 0.6.0' 
end
